// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faczmoxxcfysawyzjsau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhY3ptb3h4Y2Z5c2F3eXpqc2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzY1MTQsImV4cCI6MjA2MjM1MjUxNH0.Z3ipih14wqsk5QlVtQ8vvvIObI4TCeDALlPT9SmJG0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);