// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgrpadosasawqplzubaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZncnBhZG9zYXNhd3FwbHp1YmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODc0NjEsImV4cCI6MjA2MDk2MzQ2MX0.08efaw2d9ZsO8HTLVZY1Sd9cPvS4QO8jPO8S90nlssA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);